import type { HsfrError } from "../domain/errors.js"

export const EXIT_CODES = {
  SUCCESS: 0,
  UNEXPECTED: 1,
  INPUT_VALIDATION: 2,
  UNSAFE_CONTENT: 3,
  MAPPING: 4,
  OVERRIDE_CONFLICT: 5,
  DISTRIBUTION_BLOCKED: 6,
  SOURCE_ACCESS: 7,
} as const

const BY_ERROR_CODE: Record<HsfrError["code"], number> = {
  INPUT_VALIDATION_ERROR: EXIT_CODES.INPUT_VALIDATION,
  UNSAFE_CONTENT: EXIT_CODES.UNSAFE_CONTENT,
  MAPPING_ERROR: EXIT_CODES.MAPPING,
  OVERRIDE_CONFLICT: EXIT_CODES.OVERRIDE_CONFLICT,
  CONTENT_DISTRIBUTION_BLOCKED: EXIT_CODES.DISTRIBUTION_BLOCKED,
  SOURCE_ACCESS_ERROR: EXIT_CODES.SOURCE_ACCESS,
}

export function exitCodeForError(error: HsfrError): number {
  return BY_ERROR_CODE[error.code] ?? EXIT_CODES.UNEXPECTED
}
